### ISSUE TITLE
Node example produce error FormData is not defined

### ISSUE THREAD

**Issue by acacha** [acacha/forms#10]
node index.js
/home/sergi/Code/acacha/forms/examples/lib/acacha-forms.min.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(require("axios")):"function"==typeof define&&define.amd?define("AcachaForm",["axios"],t):"object"==typeof exports?exports.AcachaForm=t(require("axios")):e.AcachaForm=t(e.axios)}(this,function(e){return function(e){function t(r){if(n[r])return n[r].exports;var i=n[r]={i:r,l:!1,exports:{}};return e[r].call(i.exports,i,i.exports,t),i.l=!0,i.exports}var n={};return t.m=e,t.c=n,t.i=function(e){return e},t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{configurable:!1,enumerable:!0,get:r})},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="",t(t.s=3)}([function(e,t,n){"use strict";function r(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a functi

ReferenceError: FormData is not defined
    at e.value (/home/sergi/Code/acacha/forms/examples/lib/acacha-forms.min.js:1:7605)
    at new e (/home/sergi/Code/acacha/forms/examples/lib/acacha-forms.min.js:1:7378)
    at Object.<anonymous> (/home/sergi/Code/acacha/forms/examples/node/index.js:5:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)

**Comment by acacha** [comment]
Solved checking environment. In node.js Formdata could not be used
